adminUser:
  password: local:jenkinsx/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: tonny.kusdarwanto@gmail.com
  token: local:jenkinsx/pipelineUser:token
  username: txcom-bot
prow:
  hmacToken: local:jenkinsx/prow:hmacToken
